// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const hasSupabaseEnv =
      import.meta.env['VITE_SUPABASE_URL'] ||
      import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
      process.env['SUPABASE_URL'] ||
      process.env['SUPABASE_PUBLISHABLE_KEY']
    if (!hasSupabaseEnv) {
      return next({})
    }
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
